//* Skybox generated by: https://tools.wwwtyro.net/space-3d/index.html

import {useThree} from "@react-three/fiber";
import {CubeTextureLoader} from "three";

const SkyBox: React.FC<{}> = () => {
  const {scene} = useThree();
  // console.log("scene:", scene);

  scene.background = new CubeTextureLoader()
    .setPath("/skybox_images/")
    .load(["back.png", "top.png", "front.png", "bottom.png", "left.png", "right.png"]);

  return null;
};

export default SkyBox;
