//* Skybox generated by: https://tools.wwwtyro.net/space-3d/index.html

import {useThree} from "@react-three/fiber";
import {CubeTextureLoader} from "three";

const SkyBox: React.FC<{}> = () => {
  const {scene} = useThree();
  const loader = new CubeTextureLoader();

  const texture = loader.load([
    "/skybox_images/back.png",
    "/skybox_images/top.png",
    "/skybox_images/front.png",
    "/skybox_images/bottom.png",
    "/skybox_images/left.png",
    "/skybox_images/right.png",
  ]);

  scene.background = texture;
  return null;
};

export default SkyBox;
